apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: GITExamplewithlocal
  description: example.com
  annotations:
    github.com/project-slug: nithyan2582/GitTestFD
spec:
  type: service
  lifecycle: experimental
  owner: guest
